<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Log_user extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Log_user_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','log_user/tbl_log_user_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Log_user_model->json();
    }

    public function read($id) 
    {
        $row = $this->Log_user_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_user' => $row->id_user,
		'tgl_log_history' => $row->tgl_log_history,
		'action' => $row->action,
		'data' => $row->data,
		'deskripsi' => $row->deskripsi,
        'action_url' => $row->action_url,
	    );
            $this->template->load('template','log_user/tbl_log_user_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('log_user'));
        }
    }

   
  
  

    public function excel()
    {
        $this->load->helper('exportexcel');
        $namaFile = "tbl_log_user.xls";
        $judul = "tbl_log_user";
        $tablehead = 0;
        $tablebody = 1;
        $nourut = 1;
        //penulisan header
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Content-Type: application/force-download");
        header("Content-Type: application/octet-stream");
        header("Content-Type: application/download");
        header("Content-Disposition: attachment;filename=" . $namaFile . "");
        header("Content-Transfer-Encoding: binary ");

        xlsBOF();

        $kolomhead = 0;
        xlsWriteLabel($tablehead, $kolomhead++, "No");
    	xlsWriteLabel($tablehead, $kolomhead++, "Id User");
    	xlsWriteLabel($tablehead, $kolomhead++, "Tgl Log History");
    	xlsWriteLabel($tablehead, $kolomhead++, "Action");
    	xlsWriteLabel($tablehead, $kolomhead++, "Data");
    	xlsWriteLabel($tablehead, $kolomhead++, "Deskripsi");
        xlsWriteLabel($tablehead, $kolomhead++, "Action_url");

	foreach ($this->Log_user_model->get_all() as $data) {
            $kolombody = 0;

            //ubah xlsWriteLabel menjadi xlsWriteNumber untuk kolom numeric
        xlsWriteNumber($tablebody, $kolombody++, $nourut);
	    xlsWriteNumber($tablebody, $kolombody++, $data->id_user);
	    xlsWriteNumber($tablebody, $kolombody++, $data->tgl_log_history);
	    xlsWriteLabel($tablebody, $kolombody++, $data->action);
	    xlsWriteLabel($tablebody, $kolombody++, $data->data);
	    xlsWriteLabel($tablebody, $kolombody++, $data->deskripsi);
        xlsWriteLabel($tablebody, $kolombody++, $data->action_url);

	    $tablebody++;
            $nourut++;
        }

        xlsEOF();
        exit();
    }

}

/* End of file Log_user.php */
/* Location: ./application/controllers/Log_user.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-19 08:12:43 */
/* http://harviacode.com */