<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Send_email extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cat_bisnis_model');
       
    }

    public function SendToEmail()
    {
        $config = Array(  
            'protocol'  => 'smtp',  
            'smtp_host' => 'mail.kidsrepublic.sch.id',  
            'smtp_port' => 587,  
            'smtp_user' => 'simak-noreply@kidsrepublic.sch.id',   
            'smtp_pass' => 'Kids12345',   
            'mailtype'  => 'html',   
            'charset'   => 'iso-8859-1'  
        );

        $this->load->library('email',$config);


        $this->email->from('simak-noreply@kidsrepublic.sch.id', 'simak-noreply');
        $this->email->to($to);
        $this->email->bcc("it@kidsrepublic.sch.id, info@kidsrepublic.sch.id");
        // $this->email->cc('another@another-example.com');
        // $this->email->bcc('them@their-example.com');

        $this->email->subject('Respond');
        $this->email->message($balasan);

        if($this->email->send()){
            echo "mail send";
        }else{
            show_error($this->email->print_debugger());
        }
    } 



}

/* End of file Cat_bisnis.php */
/* Location: ./application/controllers/Cat_bisnis.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-19 18:50:23 */
/* http://harviacode.com */