<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Log_user_model extends CI_Model
{

    public $table = 'tbl_log_user';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,id_user,tgl_log_history,action,data,deskripsi,action_url');
        $this->datatables->from('tbl_log_user');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_log_user.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('log_user/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('log_user/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('log_user/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('tgl_log_history', $q);
	$this->db->or_like('action', $q);
	$this->db->or_like('data', $q);
	$this->db->or_like('deskripsi', $q);
    $this->db->or_like('action_url', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('tgl_log_history', $q);
	$this->db->or_like('action', $q);
	$this->db->or_like('data', $q);
	$this->db->or_like('deskripsi', $q);
    $this->db->or_like('action_url', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($datalog)
    {
        $this->db->insert($this->table, $datalog);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Log_user_model.php */
/* Location: ./application/models/Log_user_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-19 08:12:43 */
/* http://harviacode.com */